# Generated by Django 5.1.6 on 2025-02-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pagina', '0002_alter_cliente_celular_alter_cliente_coordenadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='cliente',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
