# Generated by Django 5.1.6 on 2025-02-28 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pagina', '0003_alter_ticket_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='celular',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
