# Generated by Django 5.1.6 on 2025-02-28 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pagina', '0004_ticket_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='celular',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
