# Generated by Django 5.1.6 on 2025-03-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pagina', '0006_alter_ticket_celular'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='caja',
            field=models.CharField(blank=True, choices=[('COBRADO', 'COBRADO'), ('PENDIENTE', 'PENDIENTE'), ('A PAGAR', 'A PAGAR')], default='PENDIENTE', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='estado',
            field=models.CharField(blank=True, choices=[('PENDIENTE', 'PENDIENTE'), ('LISTO', 'LISTO'), ('CANCELADO', 'CANCELADO')], default='PENDIENTE', max_length=255, null=True),
        ),
    ]
