# Generated by Django 5.1.6 on 2025-03-15 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pagina', '0007_ticket_caja_ticket_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.CharField(blank=True, choices=[('COCINA', 'COCINA'), ('BARRA', 'BARRA')], default='COCINA', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='caja',
            field=models.CharField(blank=True, choices=[('PENDIENTE', 'PENDIENTE'), ('A PAGAR', 'A PAGAR'), ('COBRADO', 'COBRADO')], default='PENDIENTE', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tipo',
            field=models.CharField(choices=[('MESA', 'MESA'), ('DELIVERY', 'DELIVERY'), ('RECOGER', 'RECOGER')], max_length=255),
        ),
    ]
