# Generated by Django 5.1.6 on 2025-03-15 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_pagina', '0008_producto_tipo_alter_ticket_caja_alter_ticket_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='tipo',
            new_name='tipo_producto',
        ),
    ]
